# Generated by Django 2.1.1 on 2018-09-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optiontype',
            old_name='type',
            new_name='optiontype',
        ),
    ]
