# Generated by Django 2.1.1 on 2018-09-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('options', models.ManyToManyField(to='main.Options')),
                ('products', models.ManyToManyField(to='main.Products')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='options',
        ),
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
